# Read the Docs configuration file
# See https://docs.readthedocs.io/en/stable/config-file/v2.html for details
version: 2
sphinx:
  # Path to your Sphinx configuration file.
  configuration: docs/conf.py

version: 2
mkdocs:
  # Path to your MkDocs configuration file.
  configuration: mkdocs.yml

build:
  os: ubuntu-22.04
  tools:
    python: "3.10"

python:
  install:
    - requirements: requirements.txt

