# Read the Docs configuration file
# See https://docs.readthedocs.io/en/stable/config-file/v2.html for details
version: 2
sphinx:
  # Path to your Sphinx configuration file.
  configuration: conf.py

build:
  os: ubuntu-22.04
  tools:
    python: "3.10"

python:
  install:
    - requirements: requirements.txt

search:
  ranking:
    _sources/*: -10
    genindex.html: -9
    blog/tag/*: -2
    blog/category/*: -3
    blog/author/*: -5
    blog/20[0-9].html: -5
    blog/archive.html: -5
    blog/author.html: -5
    blog/category.html: -5
    blog/drafts.html: -5
    blog/tag.html: -5

  ignore:
    - 404.html
    - search.html
    - index.html
